"""Upscale a Flow-generated Veo clip to 1080p via gflow (free on AI Pro)."""

from __future__ import annotations

import shutil
import tempfile
import time
from pathlib import Path
from typing import Any

from tools.base_tool import (
    BaseTool,
    Determinism,
    ExecutionMode,
    ResourceProfile,
    RetryPolicy,
    ToolResult,
    ToolRuntime,
    ToolStability,
    ToolStatus,
    ToolTier,
)
from tools.flow import gflow_client


class FlowVideoUpscale(BaseTool):
    name = "flow_video_upscale"
    version = "0.1.0"
    tier = ToolTier.ENHANCE
    capability = "video_upscale"
    provider = "google_flow"
    stability = ToolStability.EXPERIMENTAL
    execution_mode = ExecutionMode.SYNC
    determinism = Determinism.DETERMINISTIC
    runtime = ToolRuntime.API

    dependencies = []
    install_instructions = "Install gflow-cli and log in — see docs/FLOW_SETUP.md."
    capabilities = ["upscale_video"]
    supports = {"scales": ["1080p", "720p"]}
    best_for = ["final 1080x1920 masters of clips generated by flow_veo_video"]
    not_good_for = ["clips not generated in Flow (needs the Flow media_id)"]

    input_schema = {
        "type": "object",
        "required": ["media_id", "output_path"],
        "properties": {
            "media_id": {"type": "string", "description": "media_id returned by flow_veo_video"},
            "scale": {"type": "string", "enum": ["1080p", "720p"], "default": "1080p"},
            "flow_project": {"type": "string"},
            "output_path": {"type": "string"},
        },
    }
    resource_profile = ResourceProfile(cpu_cores=1, ram_mb=1500, disk_mb=500, network_required=True)
    retry_policy = RetryPolicy(max_retries=0)
    side_effects = ["opens a visible Chrome window logged into Google Flow", "writes video file"]

    def get_status(self) -> ToolStatus:
        return ToolStatus.AVAILABLE if gflow_client.is_installed() else ToolStatus.UNAVAILABLE

    def execute(self, inputs: dict[str, Any]) -> ToolResult:
        start = time.time()
        output_path = Path(inputs["output_path"])
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(prefix="flow_upscale_") as tmp:
            args = ["video", "upscale", inputs["media_id"], "--scale", inputs.get("scale", "1080p"), "-o", tmp]
            if inputs.get("flow_project"):
                args += ["--project", inputs["flow_project"]]
            try:
                # `video upscale` has no --json; success is the file it writes.
                gflow_client.run(args, json_flag=False, timeout=15 * 60)
            except gflow_client.GflowError as exc:
                return ToolResult(success=False, error=str(exc), data={"exit_code": exc.exit_code})
            videos = sorted(Path(tmp).rglob("*.mp4"), key=lambda p: p.stat().st_mtime)
            if not videos:
                return ToolResult(success=False, error="gflow upscale produced no mp4")
            shutil.move(str(videos[-1]), output_path)
        return ToolResult(
            success=True,
            data={"output": str(output_path), "output_path": str(output_path), "scale": inputs.get("scale", "1080p")},
            artifacts=[str(output_path)],
            cost_usd=0.0,
            duration_seconds=round(time.time() - start, 2),
        )
